version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

# Application server settings (docs: https://roadrunner.dev/docs/php-worker)
server:
  command: "php roadrunner-worker.php"
  relay: pipes

# Logging settings (docs: https://roadrunner.dev/docs/beep-beep-logging)
logs:
  mode: development
  level: debug
  encoding: json
  line_ending: "\n"
  output: runtime/logs/rr.log
  err_output: runtime/logs/rr_error.log

service:
  queue_consumer_default:
    command: php yii queue/listen
    process_num: 1
    exec_timeout: '0'
    remain_after_exit: true
    restart_sec: 1

http:
  address: :80
  internal_error_code: 505
  access_logs: true
  max_request_size: 1
  trusted_subnets:
    - "0.0.0.0/0"
  pool:
    debug: false
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 0s
    destroy_timeout: 5s
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 0s
      max_worker_memory: 128
      exec_ttl: 0s

 # TODO
 # Application metrics in Prometheus format (docs: https://roadrunner.dev/docs/beep-beep-metrics). Drop this section
 # for this feature disabling.
 # metrics:
   # Prometheus client address (path /metrics added automatically).
   #
   # Default: "127.0.0.1:2112"
   # address: "127.0.0.1:2112"

 # Application-specific metrics (published using an RPC connection to the server).
  # collect:
  #   app_metric:
  #     type: histogram
  #     help: "Custom application metric"
  #     labels: [ "type" ]
  #     buckets: [ 0.1, 0.2, 0.3, 1.0 ]
  #     # Objectives defines the quantile rank estimates with their respective absolute error (for summary only).
  #     objectives:
  #       - 1.4: 2.3
  #       - 2.0: 1.4


# Health check endpoint (docs: https://roadrunner.dev/docs/beep-beep-health). If response code is 200 - it means at
# least one worker ready to serve requests. 500 - there are no workers ready to service requests.
# Drop this section for this feature disabling.
status:
  address: 127.0.0.1:2114
  unavailable_status_code: 503
