version: "3.8"

services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: ./
    command:
      - vendor/bin/wait-for-it.sh
      - amqp:5672
      - --strict
      - --
      - vendor/bin/wait-for-it.sh
      - db:3306
      - --strict
      - --
      - ./rr
      - serve
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
      - ./.docker/data/composer:/home/appuser/.composer
      - ./project:/var/www
    environment:
      TZ: Europe/Moscow
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
      YII_DEBUG: 'true'
      YII_ENV: ${YII_ENV:-dev}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: "yes"
      URL_PREFIX: /app
      BOT_TOKEN: ${BOT_TOKEN}
      AMQP_USER: ${AMQP_USER}
      AMQP_PASSWORD: ${AMQP_PASSWORD}
    depends_on:
      - db
      - amqp
    extra_hosts:
      - host.docker.internal:${HOST_IP:-172.17.0.1}
    profiles:
      - full
      - console-tools
      - main
    dns:
      - 1.1.1.1
      - 8.8.8.8

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-3306}:3306
    profiles:
      - full
      - main
      - db

  amqp:
    image: rabbitmq:3-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    expose:
      - 5672
    profiles:
      - full
      - main

  loki:
    image: grafana/loki:2.7.1
    command: -config.file=/etc/loki/local-config.yaml
    profiles:
      - full

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./project/runtime/logs:/var/log/app
      - ./project/runtime/logs-rr:/var/log/rr
      - .docker/data/promtail-data:/var/lib/promtail/positions
      - .docker/loki/promtail-local-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    links:
      - loki
    profiles:
      - full

  grafana:
    image: grafana/grafana-oss:latest
    user: 1000:1000
    volumes:
      - .docker/data/grafana:/var/lib/grafana
      - .docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    profiles:
      - full
