version: "2.7"

rpc:
    listen: tcp://127.0.0.1:6001

server:
  command: "php roadrunner-worker.php"
  relay: pipes

logs:
  mode: development
  level: debug
  encoding: console
  output: stdout
  err_output: stderr

service:
  queue_consumer_default:
    command: php yii queue/listen
    process_num: 1
    exec_timeout: '0s'
    remain_after_exit: true
    restart_sec: 1

  telegram_updates:
      command: php yii viktorprogger/telegram/updates
      remain_after_exit: true
      restart_sec: 10

http:
  address: :80
  internal_error_code: 505
  access_logs: true
  max_request_size: 1
  trusted_subnets:
    [
        "10.0.0.0/8",
        "127.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "::1/128",
        "fc00::/7",
        "fe80::/10",
    ]

  pool:
    debug: true
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 0s
    destroy_timeout: 5s
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 0s
      max_worker_memory: 128
      exec_ttl: 0s



status:
  address: 127.0.0.1:2114
  unavailable_status_code: 503

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      dirs: [ "." ]
      recursive: true
      ignore: [ "vendor", "runtime" ]
      patterns: [ ".php", ".go", ".md" ]
