apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: yii_inform_loki_datasource
    # <string> url
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    isDefault: true
    editable: true
